{% set name = "msgpack-c" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/msgpack/{{ name }}/archive/cpp-{{ version }}.tar.gz
  sha256: 464f46744a6be778626d11452c4db3c2d09461080c6db42e358e21af19d542f6
  patches:
    # This is needed for a bug in gcc version used where isnan is ambiguous. (::isnan and std::isnan)
    - ambiguous_nan_inf.patch   # [linux]

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - boost-cpp
    - gtest
    - zlib
  run:
    - boost-cpp
    - zlib

test:
  commands:
    - test -f $PREFIX/include/msgpack.h                         # [unix]
    - test -f $PREFIX/include/msgpack.hpp                       # [unix]
    - test -f $PREFIX/lib/libmsgpackc.a                         # [unix]
    - test -f $PREFIX/lib/libmsgpackc.so                        # [linux]
    - test -f $PREFIX/lib/libmsgpackc.dylib                     # [osx]
    - if not exist %LIBRARY_INC%\\msgpack.h exit 1              # [win]
    - if not exist %LIBRARY_INC%\\msgpack.hpp exit 1            # [win]
    - if not exist %LIBRARY_LIB%\\msgpackc.lib exit 1           # [win]
    - if not exist %LIBRARY_LIB%\\msgpackc_static.lib exit 1    # [win]
    - if not exist %LIBRARY_BIN%\\msgpackc.dll exit 1           # [win]

about:
  home: https://github.com/msgpack/msgpack-c
  license: Boost-1.0
  license_file: LICENSE_1_0.txt
  summary: MessagePack implementation for C and C++.
  doc_url: https://github.com/msgpack/msgpack-c/blob/master/README.md
  dev_url: https://github.com/msgpack/msgpack-c

extra:
  recipe-maintainers:
    - bluescarni
    - mcs07
