{% set name = "msgpack-c" %}
{% set version = "3.1.1" %}
{% set sha256 = "bda49f996a73d2c6080ff0523e7b535917cd28c8a79c3a5da54fc29332d61d1e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/msgpack/{{ name }}/archive/cpp-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # This is needed for a bug in gcc version used where isnan is ambiguous. (::isnan and std::isnan)
    - ambiguous_nan_inf.patch   # [linux]

build:
  number: 0
  skip: True  # [win and py36]
  features:
    - vc9     # [win and py27]
    - vc14    # [win and (py35 or py36)]

requirements:
  build:
    - python  # [win]
    - vc 9    # [win and py27]
    - vc 14   # [win and (py35 or py36)]
    - gtest
    - cmake
    - toolchain
    - boost-cpp 1.66.0
    - zlib 1.2.*
  run:
    - vc 9   # [win and py27]
    - vc 14  # [win and (py35 or py36)]
    - boost-cpp 1.66.0
    - zlib 1.2.*

test:
  commands:
    - test -f $PREFIX/include/msgpack.h                         # [unix]
    - test -f $PREFIX/include/msgpack.hpp                       # [unix]
    - test -f $PREFIX/lib/libmsgpackc.a                         # [unix]
    - test -f $PREFIX/lib/libmsgpackc.so                        # [linux]
    - test -f $PREFIX/lib/libmsgpackc.dylib                     # [osx]
    - if not exist %LIBRARY_INC%\\msgpack.h exit 1              # [win]
    - if not exist %LIBRARY_INC%\\msgpack.hpp exit 1            # [win]
    - if not exist %LIBRARY_LIB%\\msgpackc.lib exit 1           # [win]
    - if not exist %LIBRARY_LIB%\\msgpackc_static.lib exit 1    # [win]
    - if not exist %LIBRARY_BIN%\\msgpackc.dll exit 1           # [win]

about:
  home: https://github.com/msgpack/msgpack-c
  license: Boost-1.0
  license_file: LICENSE_1_0.txt
  summary: 'MessagePack implementation for C and C++.'
  doc_url: https://github.com/msgpack/msgpack-c/blob/master/README.md
  dev_url: https://github.com/msgpack/msgpack-c

extra:
  recipe-maintainers:
    - bluescarni
