{% set name = "msgpack-c" %}
{% set version = "4.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/msgpack/{{ name }}/archive/cpp-{{ version }}.tar.gz
  sha256: fd0a685656f11b8aa09ed33bcbdcad3105d25d0034ca3dba9fe957623a42d253
  patches:
    # This is needed for a bug in gcc version used where isnan is ambiguous. (::isnan and std::isnan)
    - ambiguous_nan_inf.patch   # [linux]
    - windows_warnings.patch  # [win]

build:
  number: 0
  run_exports:
    # 2022/12/01
    # No information, but the project "feels" stable to me (hmaarrfk)
    # and we haven't had a pinning before version 3.3.0 and it hasn't been
    # a problem. However with the 4.X migration looming, I want to pin
    # to major numbers now
    - {{ pin_subpackage('msgpack-c', max_pin='x') }}
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - make  # [unix]
    - python  # [win]
  host:
    - boost-cpp
    - gtest
    - gmock
    - zlib
  run:
    - boost-cpp

test:
  commands:
    - test -f $PREFIX/include/msgpack.h                         # [unix]
    - test -f $PREFIX/include/msgpack.hpp                       # [unix]
    - test -f $PREFIX/lib/libmsgpackc.a                         # [unix]
    - test -f $PREFIX/lib/libmsgpackc.so                        # [linux]
    - test -f $PREFIX/lib/libmsgpackc.dylib                     # [osx]
    - if not exist %LIBRARY_INC%\\msgpack.h exit 1              # [win]
    - if not exist %LIBRARY_INC%\\msgpack.hpp exit 1            # [win]
    - if not exist %LIBRARY_LIB%\\msgpackc.lib exit 1           # [win]
    - if not exist %LIBRARY_LIB%\\msgpackc_static.lib exit 1    # [win]
    - if not exist %LIBRARY_BIN%\\msgpackc.dll exit 1           # [win]

about:
  home: https://github.com/msgpack/msgpack-c
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  summary: MessagePack implementation for C and C++.
  doc_url: https://github.com/msgpack/msgpack-c/blob/master/README.md
  dev_url: https://github.com/msgpack/msgpack-c

extra:
  recipe-maintainers:
    - hmaarrfk
    - bluescarni
    - mcs07
    - ndevenish
