context:
  name: msgpack-c
  version: "6.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/msgpack/msgpack-c/archive/c-${{ version }}.tar.gz
  sha256: c23c4070dbe01f46044bf70c5349f29453d655935b6dc710714c008bca0825a7

build:
  number: 4

requirements:
  run_exports:
    # 2022/12/01
    # No information, but the project "feels" stable to me (hmaarrfk)
    # and we haven't had a pinning before version 3.3.0 and it hasn't been
    # a problem. However with the 4.X migration looming, I want to pin
    # to major numbers now
    - ${{ pin_subpackage('msgpack-c', upper_bound='x') }}
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
    - ${{ "make" if unix }}
    - ${{ "python" if win }}
  host:
    - gmock
tests:
  - script:
      - if: unix
        then:
          - test -f ${PREFIX}/include/msgpack.h
          - test ! -f ${PREFIX}/lib/libmsgpack-c.a
          - if: linux
            then:
              - test -f ${PREFIX}/lib/libmsgpack-c.so
          - if: osx
            then:
              - test -f ${PREFIX}/lib/libmsgpack-c.dylib
        else:
          - if not exist %LIBRARY_INC%\\msgpack.h exit 1
          - if not exist %LIBRARY_LIB%\\msgpack-c.lib exit 1
          - if exist %LIBRARY_LIB%\\msgpack-c_static.lib exit 1
          - if not exist %LIBRARY_BIN%\\msgpack-c.dll exit 1

about:
  homepage: https://github.com/msgpack/msgpack-c
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  summary: MessagePack implementation for C and C++.
  documentation: https://github.com/msgpack/msgpack-c/blob/master/README.md
  repository: https://github.com/msgpack/msgpack-c

extra:
  recipe-maintainers:
    - hmaarrfk
    - bluescarni
    - ndevenish
    - traversaro
