context:
  name: msgpack-c
  version: "6.1.0"

source:
  url: https://github.com/msgpack/msgpack-c/archive/c-${{ version }}.tar.gz
  sha256: c23c4070dbe01f46044bf70c5349f29453d655935b6dc710714c008bca0825a7

build:
  number: 4

outputs:
  - package:
      name: msgpack-c
      version: ${{ version }}
    requirements:
      run_exports:
        - ${{ pin_subpackage('msgpack-c', upper_bound='x') }}
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib("c") }}
        - cmake
        - ninja
        - ${{ "make" if unix }}
        - ${{ "python" if win }}
      host:
        - gmock
    tests:
      - script:
          - if: unix
            then:
              - test -f ${PREFIX}/include/msgpack.h
              - test ! -f ${PREFIX}/lib/libmsgpack-c.a
              - if: linux
                then:
                  - test -f ${PREFIX}/lib/libmsgpack-c.so
              - if: osx
                then:
                  - test -f ${PREFIX}/lib/libmsgpack-c.dylib
            else:
              - if not exist %LIBRARY_INC%\\msgpack.h exit 1
              - if not exist %LIBRARY_LIB%\\msgpack-c.lib exit 1
              - if exist %LIBRARY_LIB%\\msgpack-c_static.lib exit 1
              - if not exist %LIBRARY_BIN%\\msgpack-c.dll exit 1
    about:
      homepage: https://github.com/msgpack/msgpack-c
      license: BSL-1.0
      license_file: LICENSE_1_0.txt
      summary: MessagePack implementation for C and C++ (shared library).
      documentation: https://github.com/msgpack/msgpack-c/blob/master/README.md
      repository: https://github.com/msgpack/msgpack-c

  - package:
      name: msgpack-c-static
      version: ${{ version }}
    requirements:
      run_exports:
        - ${{ pin_subpackage('msgpack-c-static', upper_bound='x') }}
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib("c") }}
        - cmake
        - ninja
        - ${{ "make" if unix }}
        - ${{ "python" if win }}
      host:
        - gmock
    tests:
      - script:
          - if: unix
            then:
              - test -f ${PREFIX}/include/msgpack.h
              - test -f ${PREFIX}/lib/libmsgpack-c.a
              - if: linux
                then:
                  - test ! -f ${PREFIX}/lib/libmsgpack-c.so
              - if: osx
                then:
                  - test ! -f ${PREFIX}/lib/libmsgpack-c.dylib
            else:
              - if not exist %LIBRARY_INC%\\msgpack.h exit 1
              - if exist %LIBRARY_LIB%\\msgpack-c.lib exit 1
              - if not exist %LIBRARY_LIB%\\msgpack-c_static.lib exit 1
              - if exist %LIBRARY_BIN%\\msgpack-c.dll exit 1
    about:
      homepage: https://github.com/msgpack/msgpack-c
      license: BSL-1.0
      license_file: LICENSE_1_0.txt
      summary: MessagePack implementation for C and C++ (static library).
      documentation: https://github.com/msgpack/msgpack-c/blob/master/README.md
      repository: https://github.com/msgpack/msgpack-c

about:
  homepage: https://github.com/msgpack/msgpack-c
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  summary: MessagePack implementation for C and C++.
  documentation: https://github.com/msgpack/msgpack-c/blob/master/README.md
  repository: https://github.com/msgpack/msgpack-c

extra:
  recipe-maintainers:
    - hmaarrfk
    - bluescarni
    - ndevenish
    - traversaro
