travis:
  secure:
    BINSTAR_TOKEN: G0vtf5ZiAoF7dJEIu4Ho+duR+6fJkcen8JGs64vSXDun8tfoIJ6POi8pk101MUdYWpZC0QcwxYJUh56tJ4klONcj36Y4qKbDxYjyYqvxSPzZMx+4t83vzAXUyr0UkMDzQn5ToUINzuuvMAuvPbQTVpVkjQqvP30LoU+UDj7+jlGu/S6VplYm1q2V7oa4wnrGdeXVmY869H1KW+ym058R5RP8zAQ2ngv1GCP+jqUqHtFYJQB7mF7yZNYN1qUQeFs5owIQ2atFmG/NJs8IXtW1HihARLvLBvYp+QRkDK//7WlR+LT25JO7YaPPDudqim7IIwbOClot7m729o1/x0JNCtV2FQj90ylOymypOvdxuzJgIh6YSFS72fBpat2C8dzadXqUn4z4ZSl5G8bDAL6YCg+qmqiSqT7d4IxN2b3D1AxUJ2cQ8ISqYu89nhXH4CehB+KQF+30pOaVTO3N64iPfcBvjbcL0mMafZyY4SY9qrnH42b/KY3gnaHUj5FYMdk4xohdTyWVA62Ddfcmk54c5CCnNKyEfOHkAvn9nNRqGddsZo2K8NcRA2b2BhuFQasoRH1ywbK0c/IpacKFy8P8IH3wdpKNDI61z+jwKno/GW+cJhoBqVPXPB3Bu9zs13fncYwA+3tqLAn3zu0e9hzzexys5MT0nUD4fuJWiMQC30Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
